- hosts: webservers
  tasks:
   - package:
        name: python3
        state: present

   - pip:
        name: docker==4.4.1
        state: present

   - docker_image:
        name: httpd
        source: pull   
  
   - file:
        state: directory
        path: "/home/mounted"

   - copy:
        src: "/root/dockerWeb/code.html"
        dest: "/home/mounted"

   - docker_container:
        name: webserverOS
        image: httpd
        state: started
        ports: 
           - "8080:80"
        mounts:
          - source: "/home/mounted"
            target: "/usr/local/apache2/htdocs"
            type: bind
            read_only: no
            propagation: rprivate
            #register: containerDetail
     
     ## remove below host and task line before using
- hosts: localhost
  tasks:
   - name: "Debugging the Name Just for Check"
     debug: 
       var: "{{ hostvars['webservers'].containerDetail.container.NetworkSettings.IPAddress }}"
                      
   - name: " Updating the inventory file with the IP address"
     blockinfile:
       path: "/etc/ansible/dockerip.txt"
       block: |
              [docker]
              {{ containerDetail.container.NetworkSettings.IPAddress }} ansible_shh_user=root ansible_ssh_pass=redhat ansible_connection=ssh
