- hosts: loadbalancer
  vars_files:
  - haproxyVars.yml
  tasks:
  - name: "Installing Package of HAProxy"
    package:
      name: "haproxy"
      state: present

  - name: "Copying Template of Config file from the Controller System"
    template:
      src: "haproxy.cfg"
      dest: "/etc/haproxy"

  - name: "Statring Service"
    service:
      name: "haproxy"
      state: started

  - name: "Installing Firewalld in the System"
    package:
      name: "firewalld"
      state: present

  - name: "Enable FirewallD Program and Start It"
    service:
      name: "firewalld"
      enabled: yes
      state: started

  - name: "Enabling FireWallD for the LB Port"
    firewalld:
      port: "{{ lbport }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes


- hosts: webservers
  vars_files: "haproxyVars.yml"
  tasks:
  - name: "Installing Apache HTTPD Package"
    package:
      name: "httpd"
      state: present
      
  - name: "Creating an Index PHP file"
    copy:
      src: "index.php"
      dest: "/var/www/html/index.php"

  - name: "Copying Configuration file"
    template:
       src: "custom.conf"
       dest: "/etc/httpd/"
    notify: RestartService

  - name: "Installing Firewalld in the System"
    package:
      name: "firewalld"
      state: present

  - name: "Enable FirewallD Program and Start It"
    service:
      name: "firewalld"
      enabled: yes
      state: started

  - name: "Set FireWallD to Allow Connect to WebServer Only"
    firewalld:
      port: "{{ webserverport }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  handlers:
  - name: "RestartService"
    service:
      name: "httpd"
      state: restarted
